### ISSUE TITLE
does it work with images

### ISSUE THREAD

**Issue by gour** [webuni/commonmark-attributes-extension#16]
Hello!

[Tiki](https://tiki.org/HomePage) CMS is getting a Markdown plugin and uses CommonMark library (https://packagist.org/packages/league/commonmark). Since I need support for some stuff from PHP Markdown Extra I was trying to modify plugin to use [erusev/parsedown-extra](https://packagist.org/packages/erusev/parsedown-extra) library and, for some reason it did not work and then tried with [michelf/php-markdown](https://packagist.org/packages/michelf/php-markdown) which does work so I can use syntax like:

```
![some image title](url-of-the-image.jpg){.center}

```

to e.g. pass class (or id) attribute `class="center" to the image.

Now I wonder if this extension allows similar thing since it would be preferrable to use since the official Tiki plugin already uses CommonMark?

**Comment by nonoesp** [comment]
Yes @gour. That works.
