### ISSUE TITLE
Update to Latest

### ISSUE THREAD

**Issue by dwesolowski** [webuni/commonmark-attributes-extension#17]
Would like to update to the latest commonmark.

**Comment by nonoesp** [comment]
Hi, everyone! 👋🏻

Any plans on adding support for commonmark 1.0.0?

I'm trying to wrap my head around updating it myself to do a pull request, but I'm new to the abstract syntax tree and there seem to be a lot of breaking changes jumping from `0.18` to `1.0.0`.

**Comment by hason** [comment]
@nonoesp Yes. I hope to update the library over the next week.

**Comment by nonoesp** [comment]
Awesome to hear @hason. 👌🏻

**Comment by gour** [comment]
Any update on this?

**Comment by hason** [comment]
I released the 1.0 version for commonmark 1.0.

**Comment by nonoesp** [comment]
Thanks so much for the work @hason — really appreciate it!
