### ISSUE TITLE
Update fail

### ISSUE THREAD

**Issue by mano290** [webuni/commonmark-attributes-extension#18]
Hello guys.. I tried update package in my project and i got this error, somebody can help me?
I use: laravel 5.8. and graham-campbell/markdown ^10.3

![Capturar](https://user-images.githubusercontent.com/13751782/65847980-55d22100-e31a-11e9-8c61-a331627ece43.PNG)

Thanks

**Comment by hason** [comment]
@mano290 You should update `graham-campbell/markdown` to ^11.1 and `webuni/commonmark-attributes-extension` to ^1.0

**Comment by GrahamCampbell** [comment]
Indeed. Version 11 supports Laravel 6, but it doesn't remove Laravel 5 support.
