### ISSUE TITLE
Changes in CommonMark breaks Attributes-Extension

### ISSUE THREAD

**Issue by blegen** [webuni/commonmark-attributes-extension#2]
(both fresh from github)
Fatal error: Declaration of Webuni\CommonMark\AttributesExtension\AttributesInlineParser::parse() must be compatible with League\CommonMark\Inline\Parser\InlineParserInterface::parse(League\CommonMark\InlineParserContext $inlineContext)

Trivial to fix, but then: Webuni\CommonMark\AttributesExtension\AttributesInlineProcessor::processInlines() must be ... etc

**Comment by hason** [comment]
Fixed in version 0.3.0.
