### ISSUE TITLE
Add attributes to code blocks

### ISSUE THREAD

**Issue by lukasoppermann** [webuni/commonmark-attributes-extension#3]
Hey, I would like to be able to add custom attributes e.g. `data-file="controller.phph"` to a code block.

I think this is currently not possible, but it would be super awesome if you could implement this behaviour. If however it is possible and I missed it, please let me know how I can do this.

**Comment by hason** [comment]
You can use

``````
{data-file=controller.phph}
```
echo "It works!";
```
``````
