### ISSUE TITLE
Doesn't work with 0.17

### ISSUE THREAD

**Issue by tankerkiller125** [webuni/commonmark-attributes-extension#7]
The commonmark lib has been updated to 0.17 and this extension doesn't work with it even with the composer edited. This project also appears to be forgotten or just unmaintained.

Is that the case? Or is their something I'm missing?

**Comment by jdavidbakr** [comment]
Running into the same issue here.  Is there maybe another package that we can use if this one has been abandoned?

**Comment by tankerkiller125** [comment]
Can't seem to find one

**Comment by bridgeport** [comment]
It's odd to see this not updated considering its sibling table extension was updated last month: https://github.com/webuni/commonmark-table-extension/releases

**Comment by jdavidbakr** [comment]
Pull request https://github.com/webuni/commonmark-attributes-extension/pull/8

**Comment by tankerkiller125** [comment]
Now we just need to hope that that pull request gets accepted

**Comment by pilishen** [comment]
also need this update

**Comment by jdavidbakr** [comment]
FWIW, you can always use my branch until this pull request gets merged by adding this to your composer.json file (this works for any repo that you are needing another fork for):

```
   "require": {
        ....
        "webuni/commonmark-attributes-extension": "dev-master",
        ....
    }
    ...
    "repositories": [
        {
            "url": "https://github.com/jdavidbakr/commonmark-attributes-extension",
            "type": "git"
        }
    ]
```

Just don't forget to switch it back once the main release has the update so you're staying up to date with the correct package.

**Comment by markhalliwell** [comment]
This is sorely needed and a blocker for https://www.drupal.org/project/markdown/issues/2952435

**Comment by ipalaus** [comment]
Any news? 😕

**Comment by kylerove** [comment]
@jdavidbakr New to composer. Trying to get a working install of attributes extension. Is there an easy way to install your branch?

**Comment by jdavidbakr** [comment]
@kylerove - see my comment above, just add the line in your "require" section and add a "repositories" section with the contents above.  That's the `composer.json` file.  If you've already done `composer require webuni/commonmark-attributes-extension` you'll just update the value in the existing line to `dev-master`.  Then run `composer update` to get the package.

**Comment by owenvoke** [comment]
Looks like the PR has been accepted, as there's no tagged version I think it should be relatively ok to use `^0.6.0-dev` for now.
